-- VISTA 1: Contenido Popular
SELECT * FROM MV_CONTENIDO_POPULARIDAD WHERE ROWNUM <= 5;

-- VISTA 2: Ingresos
SELECT * FROM MV_INGRESOS_MCP WHERE ROWNUM <= 5;

-- Contar registros
SELECT COUNT(*) FROM MV_CONTENIDO_POPULARIDAD;
SELECT COUNT(*) FROM MV_INGRESOS_MCP;